version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis

  django:
    build: ./
    container_name: celery_demo
    ports:
      - "8000:8001"
    command: ["/opt/venv/bin/python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./:/celery_demo
    env_file:
      - ./env/django.env
    stdin_open: true
    tty: true
    depends_on:
      - redis

  celery:
    build: ./
    container_name: celery_worker
    command: celery --app=celery_demo worker -l INFO --concurrency=2
    volumes:
      - ./:/celery_demo
    env_file:
      - ./env/django.env
    depends_on:
      - redis

